FROM rust:latest

RUN    rustup target add x86_64-unknown-linux-musl \
    && curl -L https://musl.cc/x86_64-linux-musl-cross.tgz -o musl-cross.tar.gz \
    && tar xvfz musl-cross.tar.gz -C /opt

ENV CC_x86_64_unknown_linux_musl=x86_64-linux-musl-gcc \
    AR_x86_64_unknown_linux_musl=x86_64-linux-musl-ar \
    CXX_x86_64_unknown_linux_musl=x86_64-linux-musl-g++ \
    PATH=/opt/x86_64-linux-musl-cross/bin:$PATH

WORKDIR /io

ENTRYPOINT [ "cargo", "build", "--target", "x86_64-unknown-linux-musl", "--release" ]
